rabbitmq:
  image: glopart/rabbitmq:latest

sampleecho:
  image: arkadius/sampleecho:0.8.5-SNAPSHOT

sampleapp:
  image: arkadius/sampleapp:0.8.5-SNAPSHOT
  links:
    - rabbitmq
    - sampleecho
  ports:
    - "8081:8081"